language: go
sudo: false
go:
  - 1.5
  - 1.5.3
  - 1.6
  - tip
before_install:
  - go get github.com/golang/lint/golint
install:
  - go get -v -t .
script:
  - go test -v .
  - go vet ./...
  - golint ./...